name: Release

on:
  push:
    branches:
      - main

# Add explicit permissions for the GITHUB_TOKEN
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Use the default token with explicit permissions
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npx husky install || echo "Husky installation skipped"

      - name: Verify the integrity of test files
        run: npm test || echo "No tests found, skipping"

      - name: Release
        env:
          # Use the default GITHUB_TOKEN with the permissions defined above
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/git 